services:
  client:
    container_name: client
    build: ./client
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/db/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./backend/db/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - '5432:5432'
    volumes:
      - ./docker_db:/var/lib/postgresql
