### Get current user
GET http://localhost:8080/auth/me

### POST /auth/register creates a new user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "test",
  "name_first": "2",
  "name_last": "3",
  "email": "1",
  "password": "5",
  "phone": "6",
  "rank": "E-7",
  "uic": "WCAEB1",
  "role": "['user', 'hrh']",
  "dodid": "101"
}

### POST login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "hrh",
  "password": "password"
}

### Logout and removes cookie
POST http://localhost:8080/auth/logout
