### GET all components
GET http://localhost:8080/components

### GET component by id
GET http://localhost:8080/components/5

### GET component by uic id
GET http://localhost:8080/components/uic/1

### Create a component
POST http://localhost:8080/components
Content-Type: application/json

{
  "niin": 123456789,
  "description": "example component",
  "ui": "EA",
  "auth_qty": "4",
  "image": "image",
  "arc": "B",
  "end_item_lin": "C06935"
}

### Update component by id
PATCH http://localhost:8080/components/1
Content-Type: application/json

{
  "auth_qty": 3
}

### Delete component by id
DELETE http://localhost:8080/components/1
