### GET current history
GET http://localhost:8080/current-history

### GET current history by id
GET http://localhost:8080/current-history/1

### Create a current history
POST http://localhost:8080/current-history
Content-Type: application/json

{
  "end_item_id": 1,
  "user_id": 1,
  "seen": true,
  "location": "test",
  "last_seen": "2019-12-01",
  "count_current": 1
}

### Update current history by id
PATCH http://localhost:8080/current-history/1
Content-Type: application/json

{
  "seen": false
}

### Delete current history by id
DELETE http://localhost:8080/current-history/1
