### GET all end items
GET http://localhost:8080/end-items

### GET end item by id
GET http://localhost:8080/end-items/1

### GET end item by uic id
GET http://localhost:8080/end-items/uic/1

### Create end item
POST http://localhost:8080/end-items
Content-Type: application/json

{
  "fsc": "123",
  "description": "test2",
  "niin": "123",
  "image":"test4",
  "auth_qty": "123",
  "lin": "test6"
}

### Mark end item complete by id
PATCH http://localhost:8080/end-items/1/complete

### Update end item by id
PATCH http://localhost:8080/end-items/1
Content-Type: application/json

{
  "description": "test2"
}

### Delete end item by id
DELETE http://localhost:8080/end-items/2
