### GET all serial items
GET http://localhost:8080/serial-items

### GET serial item by id
GET http://localhost:8080/serial-items/1

### GET serial item by uic id
GET http://localhost:8080/serial-items/uic/1

### Create a serial item
POST http://localhost:8080/serial-items
Content-Type: application/json

{
  "serial_number": "SN-012",
  "status": "serviceable",
  "end_item_lin": "70210N",
  "user_dodid": "5399334747"
}

### Update serial item by id
PATCH http://localhost:8080/serial-items/4
Content-Type: application/json

{
  "status": "unserviceable"
}

### Delete serial item by id
DELETE http://localhost:8080/serial-items/4
